name: Container build
on:    
  release:
      types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@master
    #   - name: Kaniko build
    #     uses: aevea/action-kaniko@master
    #     with:
    #       image: betorvs/k6-prometheus
    #       username: ${{ secrets.DOCKER_USERNAME }}
    #       password: ${{ secrets.DOCKER_PASSWORD }}
    #       tag_with_latest: true
    #       extra_args: --build-arg VERSION=$BRANCH
    #       cache: true
    #       cache_registry: aevea/cache
    steps:
      - uses: actions/checkout@v2
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: "VERSION=${{ steps.metadata.outputs.version }}"
          cache: true
          cache-repository: ${{ github.repository }}/cache