name: Container build
on:    
  release:
      types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: betorvs/k6-prometheus
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_with_latest: true
          extra_args: --build-arg VERSION=$BRANCH
          cache: true
          cache_registry: aevea/cache